services:
  adrug-evidence-research:localp:
    image: drug-evidence-research:main
    build:
      context: .
    init: true
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-3000}:3000"
    restart: unless-stopped
    volumes:
      - data:/app/data

volumes:
  data:
